#!/bin/bash
#
# glamscan    Glamscan version 0.0.2
#
# chkconfig: 345 70 30
# description: Glamscan is a simple multi-threaded wrapper to clamAV's tcp interface
# processname: glamscan

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0
prog="glamscan"
LOCKFILE=/var/lock/subsys/$prog

# Source Glamscan configuration

. /etc/glamscan

GLAMSCAN=/usr/bin/$prog

start() {
    [ -x $GLAMSCAN ] || exit 5
    [ -n "$GLAMSCAN_OPTIONS" ] || exit 4

    daemon $GLAMSCAN $GLAMSCAN_OPTIONS 2>&1 &

    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    echo
    return $RETVAL
}

stop() {
    echo -n "Shutting down $prog: "
    killproc $prog -INT
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
    echo
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
